global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'spring-boot'
    scrape_interval: 5s
    static_configs:
      - targets: ['my-spring-boot-app:8080']